### ISSUE TITLE
AliasColors allows only hardcoded keys

### ISSUE THREAD

**Issue by cmur2** [spoved/crafana.cr#1]
I'm not entirely sure if I understood it correctly but isn't https://github.com/spoved/crafana.cr/blob/master/src/crafana/models/alias_colors.cr supposed to support arbitrary key value pairs to map colors to the targets with a certain name in the legend?

Would it be possible to extend this?

**Comment by cmur2** [comment]
I currently solved this in my fork like this https://github.com/cmur2/crafana.cr/commit/6f2d06580c331c975eb3b6947d0f35e287a3f37e which works but maybe there is a more elegant solution @kalinon ?

**Comment by kalinon** [comment]
Let me review. I never really used alias colors that much so ill see if i can find anything in the api documentation

**Comment by cmur2** [comment]
Thanks for that and also your effort in building this shard, it's very well built and useful!

If it helps this is a real world snippet from one of my dashboards using alias colors:
```json
{
  "panels": [
    {
      "aliasColors": {
        "idle": "#ffcc00",
        "iowait": "#330099",
        "nice": "#ff8000",
        "softirq": "#aa2b00",
        "system": "#00cc00",
        "user": "#0066b3"
      },
      "bars": false,
      "dashLength": 10
    }
  ]
}
```

**Comment by kalinon** [comment]
Perfect, I dont see anything in the official API docs for it.

How about possibly changing it to:

```crystal
Hash(String, String | Crafana::RGBA | Crafana::RGB)
```

We could even ditch the `AliasColors` object or alias it to the hash.

```crystal
alias AliasColors = Hash(String, String | Crafana::RGBA | Crafana::RGB)
```

**Comment by kalinon** [comment]
I should probably also make an issue to make color parsing easier. So if people want to use hex colors they can, or whatever format they want. If we do `String | Crafana::RGBA | Crafana::RGB` it might actually break things on de-serialization.

**Comment by cmur2** [comment]
I think dropping `AliasColors` object might make sense as long as we can avoid breaking changes in color parsing.

**Comment by kalinon** [comment]
> 
> 
> I think dropping `AliasColors` object might make sense as long as we can avoid breaking changes in color parsing.

Agreed. Perhaps adding a Hex color object and abstracting the json decode into a parent module. We can merge the Hash(String, String) in the meantime if youd like to get it into master.

**Comment by cmur2** [comment]
I will open a PR for the `Hash(String, String)` change.
